name: tryfinal
channels:
  - conda-forge
  - pytorch
  - default
dependencies:
  - python=3.8
  - pip
  - einops==0.6.0
  - faiss==1.7.2
  - fvcore==0.1.5.post20221221
  - h5py==3.11.0
  - matplotlib==3.6.2
  - numpy
  - plyfile==0.7.4
  - scipy==1.9.3
  - setuptools==60.2.0
  - sympy==1.12
  - tqdm==4.65.0
  - transformers==4.26.1
  - pip:
      - faiss==1.7.2
      - fast_pytorch_kmeans==0.2.0.1
      - scikit_learn==1.1.3
      - torchvision==0.18.0
      - trimesh==3.17.0
      - mmcv-full==1.4.8
      - mmdet==2.19.0
      - open3d==0.16.0 
      - torch==2.3.0
      - torchvision==0.18.0
      - scikit_learn==1.1.3
