name: tryfinal
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - apex==0.9.10dev
  - cuml==0.6.1.post1
  - einops==0.8.0
  - faiss==1.5.3
  - fast_pytorch_kmeans==0.2.0.1
  - fvcore==0.1.5.post20221221
  - h5py==3.12.1
  - matplotlib==3.1.2
  - mmcv==2.2.0
  - mmdet==3.3.0
  - mmseg==1.3.0
  - numpy==1.17.4
  - omegaconf==2.3.0
  - open3d==0.18.0
  - Pillow==11.0.0  
  - plyfile==1.1
  - PyYAML==6.0.2
  - scikit_learn==1.5.2
  - scipy==1.14.1
  - setuptools==45.2.0
  - submitit==1.5.2
  - sympy==1.13.3
  - torch==2.5.0
  - torchmetrics==1.5.1
  - torchvision==0.20.0
  - tqdm==4.66.5
  - transformers==4.45.2
  - trimesh==4.5.1
  - xformers==0.0.28.post2
  - pip:
      - apex==0.9.10dev
      - cuml==0.6.1.post1
      - faiss==1.5.3
      - fast_pytorch_kmeans==0.2.0.1
      - mmseg==1.3.0
      - scikit_learn==1.5.2
      - submitit==1.5.2
      - torchmetrics==1.5.1
      - torchvision==0.20.0
      - trimesh==4.5.1
      - xformers==0.0.28.post2
